"""Jira integration — creates issues for new incidents via REST API v3.

Configuration::

    JIRA_URL            — e.g. https://yourorg.atlassian.net  (required)
    JIRA_PROJECT_KEY    — e.g. OPS                            (required)
    JIRA_EMAIL          — Atlassian account email             (required)
    JIRA_API_TOKEN      — API token (not password)            (required)
    JIRA_ENABLED        — "true" / "false"
    JIRA_ISSUE_TYPE     — defaults to "Bug"
    JIRA_LABELS         — comma-separated, e.g. "sre,k8s"

Config dict keys mirror the env var names (lowercase without prefix).
"""

from __future__ import annotations

import base64
import json
import logging
import os
import urllib.request
from typing import Any, Dict, List, Optional

from integrations.base import BaseIntegration, IntegrationResult

logger = logging.getLogger(__name__)

_SEVERITY_PRIORITY = {
    "critical": "Highest",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}


class JiraIntegration(BaseIntegration):
    """Creates (and optionally resolves) Jira issues for SRE incidents."""

    name = "jira"

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        cfg = config or {}
        cfg.setdefault("url", os.getenv("JIRA_URL", "").rstrip("/"))
        cfg.setdefault("project_key", os.getenv("JIRA_PROJECT_KEY", ""))
        cfg.setdefault("email", os.getenv("JIRA_EMAIL", ""))
        cfg.setdefault("api_token", os.getenv("JIRA_API_TOKEN", ""))
        cfg.setdefault("enabled", os.getenv("JIRA_ENABLED", "false").lower() == "true")
        cfg.setdefault("issue_type", os.getenv("JIRA_ISSUE_TYPE", "Bug"))
        raw_labels = os.getenv("JIRA_LABELS", "sre,kubernetes")
        cfg.setdefault("labels", [label.strip() for label in raw_labels.split(",") if label.strip()])
        super().__init__(cfg)
        self._url: str = cfg["url"]
        self._project: str = cfg["project_key"]
        self._email: str = cfg["email"]
        self._token: str = cfg["api_token"]
        self._issue_type: str = cfg["issue_type"]
        self._labels: List[str] = cfg["labels"]

    def validate_config(self) -> bool:
        if not super().validate_config():
            return False
        missing = [k for k in ("url", "project_key", "email", "api_token") if not self.config.get(k)]
        if missing:
            logger.warning("Jira integration enabled but missing keys: %s", missing)
            return False
        return True

    # ------------------------------------------------------------------
    # BaseIntegration interface
    # ------------------------------------------------------------------

    def notify_incident(self, incident: Any) -> IntegrationResult:
        return self._safe_call(self._create_issue, incident)

    def notify_remediation(self, incident: Any, action: str, outcome: str) -> IntegrationResult:
        # Add a comment to the existing issue if we stored its key
        jira_key = getattr(incident, "_jira_key", None)
        if jira_key:
            return self._safe_call(self._add_comment, jira_key, action, outcome)
        return IntegrationResult(integration=self.name, success=True)

    # ------------------------------------------------------------------
    # Issue operations
    # ------------------------------------------------------------------

    def _create_issue(self, incident: Any) -> IntegrationResult:
        ns = getattr(incident, "namespace", "?")
        wl = getattr(incident, "workload", "?")
        itype = getattr(incident, "incident_type", "?")
        severity = getattr(incident, "severity", "medium")
        confidence = getattr(incident, "confidence", 0.0)
        root_cause = getattr(incident, "root_cause", "") or "(pending analysis)"
        iid = getattr(incident, "id", "")

        summary = f"[SRE] {itype} in {ns}/{wl} — {severity.upper()}"[:255]
        description = (
            f"h2. Incident Summary\n\n"
            f"*Incident ID:* {iid}\n"
            f"*Type:* {itype}\n"
            f"*Namespace / Workload:* {ns}/{wl}\n"
            f"*Severity:* {severity}\n"
            f"*Confidence:* {confidence:.0%}\n\n"
            f"h2. Root Cause\n\n{root_cause}\n\n"
            f"_Auto-generated by AI K8s SRE Operator_"
        )

        payload = {
            "fields": {
                "project": {"key": self._project},
                "summary": summary,
                "description": description,
                "issuetype": {"name": self._issue_type},
                "priority": {"name": _SEVERITY_PRIORITY.get(severity, "Medium")},
                "labels": self._labels,
            }
        }

        result = self._request("POST", "/rest/api/3/issue", payload)
        if result.success:
            issue_key = result.metadata.get("key", "")
            result.url = f"{self._url}/browse/{issue_key}" if issue_key else None
            # Attach Jira key to incident object for later comments
            try:
                incident._jira_key = issue_key
            except AttributeError:
                pass
        return result

    def _add_comment(self, issue_key: str, action: str, outcome: str) -> IntegrationResult:
        icon = {"success": "(y)", "failure": "(n)", "skipped": "(?)"}.get(outcome, "")
        body = f"{icon} *Remediation {outcome}*: `{action}`"
        payload = {"body": body}
        return self._request("POST", f"/rest/api/3/issue/{issue_key}/comment", payload)

    # ------------------------------------------------------------------
    # HTTP
    # ------------------------------------------------------------------

    def _auth_header(self) -> str:
        token = base64.b64encode(f"{self._email}:{self._token}".encode()).decode()
        return f"Basic {token}"

    def _request(self, method: str, path: str, payload: Dict[str, Any]) -> IntegrationResult:
        url = self._url + path
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=body,
            method=method,
            headers={
                "Content-Type": "application/json",
                "Authorization": self._auth_header(),
                "Accept": "application/json",
            },
        )
        with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310
            response_body = resp.read().decode("utf-8", errors="replace")
            try:
                data = json.loads(response_body)
            except json.JSONDecodeError:
                data = {}

            if resp.status in (200, 201, 204):
                return IntegrationResult(
                    integration=self.name,
                    success=True,
                    external_id=data.get("id"),
                    metadata={"key": data.get("key", "")},
                )
            return IntegrationResult(
                integration=self.name,
                success=False,
                error=f"HTTP {resp.status}: {response_body[:300]}",
            )
